/* Generated by Together */
package net.vicp.madz.infra.messaging.core;

import javax.jms.JMSException;

public class MessageSender implements Runnable {

	private MessageConnectivity messageConnectivity;
	private IEvent event;

	public MessageSender(MessageConnectivity mc, IEvent event) {
		this.messageConnectivity = mc;
		this.event = event;
	}

	public void run() {
		try {
			System.out.println(event.getClass().getName());
			this.messageConnectivity.sendDirectionalObjectMessage(this.event, this.event.getMessageProperties());
		} catch (JMSException ex) {
			java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, "exception caught", ex);
		}
	}
}
